Modified required version of unicorn
When running firmwire, I got an error from unicorn, by checking the unicorn's repo, I saw they made an update about 1 month ago producing an error when running firmwire.py of type: AttributeError: module 'importlib.resources' has no attribute 'files'